<a href="https://colab.research.google.com/github/dkhanna511/Pytorch_tutorials_Revision/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


Tensor is a multi-dimensional matrix containing elements of a single data type


### List

In [4]:
my_list = [1,2,3,4,5,6]
print(my_list)

multi_dimension_list = [[1,2,3,4,5,6], [1,2,3,4,5,6]]
print(multi_dimension_list)

[1, 2, 3, 4, 5, 6]
[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]]


## Numpy array

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.66143536, 0.05003894, 0.98569579, 0.62972508],
       [0.93548184, 0.10653248, 0.80758897, 0.03163874],
       [0.01006065, 0.97011471, 0.34329207, 0.53209512]])

In [7]:
np1.dtype

dtype('float64')

In [9]:
np2 = np.random.rand(3)
np2

array([0.02510069, 0.59727512, 0.80573972])

## Tensor

In [16]:
tensor_2d = torch.randn(3, 4)
print(tensor_2d)
tensor_2d.dtype

tensor([[-0.8112, -0.5484, -0.5556, -0.8097],
        [-0.2088, -1.5587,  1.2150, -1.1076],
        [ 1.1235,  2.6088, -2.1321,  0.0212]])


torch.float32

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6614, 0.0500, 0.9857, 0.6297],
        [0.9355, 0.1065, 0.8076, 0.0316],
        [0.0101, 0.9701, 0.3433, 0.5321]], dtype=torch.float64)