<a href="https://colab.research.google.com/github/dkhanna511/Pytorch_tutorials_Revision/blob/main/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## Reshaping and Slices

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
## Reshaping (or View) in Torch
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
## Reshape if we dont know the number of items using -1

##Reshaping using reshape
my_torch2  = torch.arange(15)
my_torch2 = my_torch2.reshape(3, -1)
print(my_torch2)

my_torch2 = my_torch2.reshape(-1, 3)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [16]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
## Reashaping using view

my_torch4 = my_torch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
## with reshape and view, they will update

In [26]:
my_torch5= torch.arange(10)
my_torch6 =my_torch5.reshape(2, 5)
print(my_torch6)

## Changing the original tensor my_torch5
my_torch5[1] = 4141

my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [28]:
my_torch6    ### Here you will see that this is updated automatically, whhich is interesting (and I didnt know this before)

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

# Slicing

In [29]:
## Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
## ?Grab a specific item
my_torch7[7]   ## Its grabbing the TENSOR 7, and not just an integer number 7

tensor(7)

In [37]:
my_torch8 = my_torch7.reshape(5, 2)
print(my_torch8)
print(my_torch8[:, 1])    ## This returns the row

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([1, 3, 5, 7, 9])


In [39]:
### Keeping the structure of the tensor and do slicing
my_torch8[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])