<a href="https://colab.research.google.com/github/dkhanna511/Pytorch_tutorials_Revision/blob/main/Tensor_Math_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


In [5]:
tensor_a = torch.tensor([1,2,3,4,5,6,7,8])
tensor_b = torch.tensor([9, 10, 11, 12, 13, 14, 15, 16])
tensor_a + tensor_b   ### Addition short hand

tensor([10, 12, 14, 16, 18, 20, 22, 24])

In [6]:
### Addition long hand
torch.add(tensor_a, tensor_b)

tensor([10, 12, 14, 16, 18, 20, 22, 24])

In [7]:
## Subtract short
tensor_b - tensor_a

tensor([8, 8, 8, 8, 8, 8, 8, 8])

In [9]:
## Subtract long head
torch.subtract(tensor_b, tensor_a)
torch.sub(tensor_b, tensor_a)   ## Both are for subtraction

tensor([8, 8, 8, 8, 8, 8, 8, 8])

In [10]:
### Multiplication short hand
tensor_a * tensor_b
# element wise multiplication

tensor([  9,  20,  33,  48,  65,  84, 105, 128])

In [11]:
## Multiplication long head
torch.mul(tensor_a, tensor_b)    ## element wise multiplication

tensor([  9,  20,  33,  48,  65,  84, 105, 128])

In [14]:
### Division short hand
tensor_b / tensor_a     ## It converts the values into floating points

tensor([9.0000, 5.0000, 3.6667, 3.0000, 2.6000, 2.3333, 2.1429, 2.0000])

In [16]:
## Division long head
torch.div(tensor_b, tensor_a) ## Works the same way

tensor([9.0000, 5.0000, 3.6667, 3.0000, 2.6000, 2.3333, 2.1429, 2.0000])

In [17]:
### Modulus
tensor_b % tensor_a

tensor([0, 0, 2, 0, 3, 2, 1, 0])

In [18]:
torch.remainder(tensor_b, tensor_a)


tensor([0, 0, 2, 0, 3, 2, 1, 0])

In [21]:
### Exponents
## Using longhand
torch.pow(tensor_b, tensor_a)


tensor([         9,        100,       1331,      20736,     371293,    7529536,
         170859375, 4294967296])

In [22]:
## using shorthand

tensor_b ** tensor_a

tensor([         9,        100,       1331,      20736,     371293,    7529536,
         170859375, 4294967296])

In [23]:
### Another way to write longhand
tensor_a.add(tensor_b)  ## Doing addition in a different longhead way

tensor([10, 12, 14, 16, 18, 20, 22, 24])

## Assignments

In [27]:
# tensor_a = tensor_a + tensor_b ## this is one way


## The other way

tensor_a.add_(tensor_b)

# tensor_a

tensor([28, 32, 36, 40, 44, 48, 52, 56])